// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// PackageAPI is an autogenerated mock type for the PackageAPI type
type PackageAPI struct {
	mock.Mock
}

// GetFileNamesForPackage provides a mock function with given fields: pkg
func (_m *PackageAPI) GetFileNamesForPackage(pkg string) ([]string, error) {
	ret := _m.Called(pkg)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pkg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackages provides a mock function with given fields: exclusionPatterns
func (_m *PackageAPI) GetPackages(exclusionPatterns []string) ([]string, error) {
	ret := _m.Called(exclusionPatterns)

	var r0 []string
	if rf, ok := ret.Get(0).(func([]string) []string); ok {
		r0 = rf(exclusionPatterns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(exclusionPatterns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
