// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	analysistypes "github.com/eltorocorp/drygopher/drygopher/coverage/analysis/analysistypes"

	mock "github.com/stretchr/testify/mock"
)

// AnalysisAPI is an autogenerated mock type for the AnalysisAPI type
type AnalysisAPI struct {
	mock.Mock
}

// GetCoverageStatistics provides a mock function with given fields: packages
func (_m *AnalysisAPI) GetCoverageStatistics(packages []string) (analysistypes.GetCoverageStatisticsOutput, error) {
	ret := _m.Called(packages)

	var r0 analysistypes.GetCoverageStatisticsOutput
	if rf, ok := ret.Get(0).(func([]string) analysistypes.GetCoverageStatisticsOutput); ok {
		r0 = rf(packages)
	} else {
		r0 = ret.Get(0).(analysistypes.GetCoverageStatisticsOutput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(packages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
