// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import pckg "github.com/eltorocorp/drygopher/drygopher/coverage/pckg"

// ProfileAPI is an autogenerated mock type for the ProfileAPI type
type ProfileAPI struct {
	mock.Mock
}

// BuildAndSaveCoverageProfile provides a mock function with given fields: allPackages, coverageProfileName
func (_m *ProfileAPI) BuildAndSaveCoverageProfile(allPackages pckg.Group, coverageProfileName string) error {
	ret := _m.Called(allPackages, coverageProfileName)

	var r0 error
	if rf, ok := ret.Get(0).(func(pckg.Group, string) error); ok {
		r0 = rf(allPackages, coverageProfileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutputPercentageFile provides a mock function with given fields: coveragePercentage
func (_m *ProfileAPI) OutputPercentageFile(coveragePercentage float64) error {
	ret := _m.Called(coveragePercentage)

	var r0 error
	if rf, ok := ret.Get(0).(func(float64) error); ok {
		r0 = rf(coveragePercentage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
