// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import pckg "github.com/eltorocorp/drygopher/drygopher/coverage/pckg"

// ReportAPI is an autogenerated mock type for the ReportAPI type
type ReportAPI struct {
	mock.Mock
}

// OutputCoverageReport provides a mock function with given fields: allPackages, exclusionPatterns
func (_m *ReportAPI) OutputCoverageReport(allPackages pckg.Group, exclusionPatterns []string) {
	_m.Called(allPackages, exclusionPatterns)
}

// PrintExcludedPackages provides a mock function with given fields: exclusionPattern
func (_m *ReportAPI) PrintExcludedPackages(exclusionPattern string) {
	_m.Called(exclusionPattern)
}
